### PR TITLE
Sort list of requests

### PR DESCRIPTION
**Pull request by dracos**
This sorts the requests returned by LWPx::Profile in order of their first sample.
I thought this seemed better than random ordering :)

### CODE REVIEW

**Comment by dracos** [comment]
The Travis failed because `perl-travis-helper` sets AUTHOR_TESTING=1, and trying to install Devel::StackTrace::AsHTML with that runs a test that needs Test::Synopsis but that hasn't been installed (it's listed under its `develop` which I think is correct, so not sure where the issue lies, except you probably don't want to be running author tests/tests at all for dependency installations? Should the help init come after dependency install?)

I turned off testing for dependency installs, feel free to change/ditch that as you prefer!

**Comment by ctriv** [comment]
Looks great.  I'll roll a new release with this after the weekend.

**Comment by dracos** [comment]
Thanks! Any news? Would like to include the new version in our project :)

**Comment by ctriv** [comment]
This just went out to cpan, sorry for the delay!

**Comment by dracos** [comment]
Not at all, thanks again!

**Pull request merged**
